/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

module.exports.nthFibonacci = nthFibonacci;
module.exports.even_fibo_terms_sum = even_fibo_terms_sum;

var cache = [];

function nthFibonacci(n) {

    if ( cache[n] )
        return cache[n];

    if ( n < 1)
        return 0;
    if ( n <= 2)
        return 1;

    cache[n]= nthFibonacci(n - 1) + nthFibonacci(n - 2);

    return cache[n];
}

function even_fibo_terms_sum( max ){
    var total = 0;
    var nth = 0;
    for (var i = 0;  nth < max ; i++){
        nth = nthFibonacci(i);
        if ( nth % 2 ===0 ){
            total += nth;
        }   
    };

    return total;
}

var total = even_fibo_terms_sum( 4000000 );
console.log(total);